// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ17HRRjeFCdhfPqHs75Bj6TFmVHmoZrA',
    appId: '1:940004062086:web:bf7d523b70887abed3b207',
    messagingSenderId: '940004062086',
    projectId: 'mdcomposer-flutter',
    authDomain: 'mdcomposer-flutter.firebaseapp.com',
    storageBucket: 'mdcomposer-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiS9RijZWldH301b80G1AS3YtFgl4GrhQ',
    appId: '1:940004062086:android:2d8954e6ebf93220d3b207',
    messagingSenderId: '940004062086',
    projectId: 'mdcomposer-flutter',
    storageBucket: 'mdcomposer-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkINBkj9knPFPpecf5s50DW-KZU1XVpiM',
    appId: '1:940004062086:ios:c3443fd483d89858d3b207',
    messagingSenderId: '940004062086',
    projectId: 'mdcomposer-flutter',
    storageBucket: 'mdcomposer-flutter.appspot.com',
    iosClientId: '940004062086-pih2f12geu2a9lon5r6q1np1jd4eq6b1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdComposerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkINBkj9knPFPpecf5s50DW-KZU1XVpiM',
    appId: '1:940004062086:ios:c3443fd483d89858d3b207',
    messagingSenderId: '940004062086',
    projectId: 'mdcomposer-flutter',
    storageBucket: 'mdcomposer-flutter.appspot.com',
    iosClientId: '940004062086-pih2f12geu2a9lon5r6q1np1jd4eq6b1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdComposerFlutter',
  );
}
